name: "notify private composer repository"

on:
  release:
    types:
      - released

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Package Rebuild
        uses: wikando/composer-repository/.github/actions/build-package@main
        with:
          github-app-key: ${{ secrets.GH_APP_KEY_REPO_WRITE }}
          package: wikando/symfony-precognition

